title: Sdot
email: your-email@example.com
author: "assets/images/s1.png"
description: >- # this means to ignore newlines until "baseurl:"
  A Personal blog and portfolio, where i'll share interests, hobbies, stories as well projects i've worked on.
baseurl: "/spws" # the subpath of your site, e.g. /blog
url: "https://slavikr.github.io/spws" # the base hostname & protocol for your site, e.g. http://example.com
#github_username:  jekyll
collections:
  projects:
    output: true

sass:
  style: compact
  
# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
